#!/bin/env python

lformat ="{:<10}nlurkin {:<6}8nm        lxplus007.cern.ch    -        {:<11}Jan 18 16:17"

print "JOBID     USER    STAT  QUEUE      FROM_HOST   EXEC_HOST   JOB_NAME   SUBMIT_TIME"
with open("jobs.list", 'r') as fd:
	for line in fd:
		num,ind,name,stat = line.split()
		if int(ind)!=-1:
			name = "{}[{}]".format(name,ind)
		print lformat.format(num,stat,name)

