#!/bin/env python
from random import randint
import re
import sys


rannum=randint(10000,99999)

def setName(opt):
    print opt
    m = re.search("(.*)\[(.*)\]", opt)
    if m:
        name = m.group(1)
        tarray = m.group(2).split(',')
        array  = []
        for val in tarray:
            indices = val.split('-')
            
            if len(indices)==1:
                array.append(int(indices[0]))
            else:
                array.extend(range(int(indices[0]), int(indices[1])+1))
    else:
        name = "blah"
        array = [-1,-1]
        
    return name,array

name = "blah"
array = [-1,-1]
queue = "8nm"

if len(sys.argv)>1:
    for opt,optn in zip(sys.argv[:-1],sys.argv[1:]):
        if opt=='-J':
            name,array = setName(optn)
        elif opt=='-q':
            queue = optn
        
print "bsub> Job <{}> is submitted to default queue <{}>.".format(rannum,queue)

with open("jobs.list", "a") as fd:
    print array
    for x in array:
        fd.write("{} {} {} PEND\n".format(rannum, x, name))
        
        